name: Library Catalog github action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build the app
      run: npm install
    - name: Start server
      run: npm run start-server &
    - name: Start frontend
      run: npm run start-frontend &
    - name: Install playwright
      run: npx playwright install
    - name: Run test
      run: npx playwright test

  deploy-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BACKEND_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
