name: Library Catalog github action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build the app
      run: npm install
    - name: Start server
      run: node server.js
    - name: Install playwright
      run: npx playwright install
    - name: Run test
      run: npx playwright test
